name: Automate Weather Script

on:
  schedule:
    - cron: '0 10 * * *' # Runs daily at 10am UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  run-weather-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Run the weather.sh script
    - name: Execute weather.sh script
      run: |
        chmod +x data/weather/weather.sh
        ./data/weather/weather.sh

    # Commit and push changes
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name "Serhii Spitsyn"
        git config --global user.email "G00439342@atu.ie"
        git add .
        git commit -m "Update weather data on $(date +'%Y-%m-%d %H:%M:%S')"
        git push https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ShamansIT/Computer_Infrastructure.git